// Generated by gencpp from file astra_camera/GetDouble.msg
// DO NOT EDIT!


#ifndef ASTRA_CAMERA_MESSAGE_GETDOUBLE_H
#define ASTRA_CAMERA_MESSAGE_GETDOUBLE_H

#include <ros/service_traits.h>


#include <astra_camera/GetDoubleRequest.h>
#include <astra_camera/GetDoubleResponse.h>


namespace astra_camera
{

struct GetDouble
{

typedef GetDoubleRequest Request;
typedef GetDoubleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetDouble
} // namespace astra_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::astra_camera::GetDouble > {
  static const char* value()
  {
    return "edb830bb55b38159c2bb5a997bcb994d";
  }

  static const char* value(const ::astra_camera::GetDouble&) { return value(); }
};

template<>
struct DataType< ::astra_camera::GetDouble > {
  static const char* value()
  {
    return "astra_camera/GetDouble";
  }

  static const char* value(const ::astra_camera::GetDouble&) { return value(); }
};


// service_traits::MD5Sum< ::astra_camera::GetDoubleRequest> should match
// service_traits::MD5Sum< ::astra_camera::GetDouble >
template<>
struct MD5Sum< ::astra_camera::GetDoubleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::astra_camera::GetDouble >::value();
  }
  static const char* value(const ::astra_camera::GetDoubleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::astra_camera::GetDoubleRequest> should match
// service_traits::DataType< ::astra_camera::GetDouble >
template<>
struct DataType< ::astra_camera::GetDoubleRequest>
{
  static const char* value()
  {
    return DataType< ::astra_camera::GetDouble >::value();
  }
  static const char* value(const ::astra_camera::GetDoubleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::astra_camera::GetDoubleResponse> should match
// service_traits::MD5Sum< ::astra_camera::GetDouble >
template<>
struct MD5Sum< ::astra_camera::GetDoubleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::astra_camera::GetDouble >::value();
  }
  static const char* value(const ::astra_camera::GetDoubleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::astra_camera::GetDoubleResponse> should match
// service_traits::DataType< ::astra_camera::GetDouble >
template<>
struct DataType< ::astra_camera::GetDoubleResponse>
{
  static const char* value()
  {
    return DataType< ::astra_camera::GetDouble >::value();
  }
  static const char* value(const ::astra_camera::GetDoubleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASTRA_CAMERA_MESSAGE_GETDOUBLE_H
