// Generated by gencpp from file robot_control/msg4pid.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MESSAGE_MSG4PID_H
#define ROBOT_CONTROL_MESSAGE_MSG4PID_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_control
{
template <class ContainerAllocator>
struct msg4pid_
{
  typedef msg4pid_<ContainerAllocator> Type;

  msg4pid_()
    : kp(0.0)
    , ki(0.0)
    , kd(0.0)
    , feedback(0.0)
    , setpoint(0.0)  {
    }
  msg4pid_(const ContainerAllocator& _alloc)
    : kp(0.0)
    , ki(0.0)
    , kd(0.0)
    , feedback(0.0)
    , setpoint(0.0)  {
  (void)_alloc;
    }



   typedef double _kp_type;
  _kp_type kp;

   typedef double _ki_type;
  _ki_type ki;

   typedef double _kd_type;
  _kd_type kd;

   typedef double _feedback_type;
  _feedback_type feedback;

   typedef double _setpoint_type;
  _setpoint_type setpoint;





  typedef boost::shared_ptr< ::robot_control::msg4pid_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_control::msg4pid_<ContainerAllocator> const> ConstPtr;

}; // struct msg4pid_

typedef ::robot_control::msg4pid_<std::allocator<void> > msg4pid;

typedef boost::shared_ptr< ::robot_control::msg4pid > msg4pidPtr;
typedef boost::shared_ptr< ::robot_control::msg4pid const> msg4pidConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_control::msg4pid_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_control::msg4pid_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_control::msg4pid_<ContainerAllocator1> & lhs, const ::robot_control::msg4pid_<ContainerAllocator2> & rhs)
{
  return lhs.kp == rhs.kp &&
    lhs.ki == rhs.ki &&
    lhs.kd == rhs.kd &&
    lhs.feedback == rhs.feedback &&
    lhs.setpoint == rhs.setpoint;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_control::msg4pid_<ContainerAllocator1> & lhs, const ::robot_control::msg4pid_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::msg4pid_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::msg4pid_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control::msg4pid_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control::msg4pid_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::msg4pid_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::msg4pid_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_control::msg4pid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f4aa24e539f2be8fa5557ca6a4d757bc";
  }

  static const char* value(const ::robot_control::msg4pid_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf4aa24e539f2be8fULL;
  static const uint64_t static_value2 = 0xa5557ca6a4d757bcULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_control::msg4pid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_control/msg4pid";
  }

  static const char* value(const ::robot_control::msg4pid_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_control::msg4pid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 kp\n"
"float64 ki\n"
"float64 kd\n"
"float64 feedback\n"
"float64 setpoint\n"
;
  }

  static const char* value(const ::robot_control::msg4pid_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_control::msg4pid_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.kp);
      stream.next(m.ki);
      stream.next(m.kd);
      stream.next(m.feedback);
      stream.next(m.setpoint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg4pid_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_control::msg4pid_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_control::msg4pid_<ContainerAllocator>& v)
  {
    s << indent << "kp: ";
    Printer<double>::stream(s, indent + "  ", v.kp);
    s << indent << "ki: ";
    Printer<double>::stream(s, indent + "  ", v.ki);
    s << indent << "kd: ";
    Printer<double>::stream(s, indent + "  ", v.kd);
    s << indent << "feedback: ";
    Printer<double>::stream(s, indent + "  ", v.feedback);
    s << indent << "setpoint: ";
    Printer<double>::stream(s, indent + "  ", v.setpoint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONTROL_MESSAGE_MSG4PID_H
