(cl:in-package ros_stm32_serial-msg)
(cl:export '(FLAG-VAL
          FLAG
          STATUS-VAL
          STATUS
          LINEARX-VAL
          LINEARX
          LINEARY-VAL
          LINEARY
          ANGULARZ-VAL
          ANGULARZ
          LASERFRONT-VAL
          LASERFRONT
          LASERL-VAL
          LASERL
          LASERR-VAL
          LASERR
          LASERREAR-VAL
          LASERREAR
          ROLLER-VAL
          ROLLER
          MODE-VAL
          MODE
          KEEPORNOT-VAL
          KEEPORNOT
          PLACEORNOT-VAL
          PLACEORNOT
          ROBOTSTATUS-VAL
          ROBOTSTATUS
))