// Generated by gencpp from file target_detection/Locked.msg
// DO NOT EDIT!


#ifndef TARGET_DETECTION_MESSAGE_LOCKED_H
#define TARGET_DETECTION_MESSAGE_LOCKED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <target_detection/msgLocked.h>

namespace target_detection
{
template <class ContainerAllocator>
struct Locked_
{
  typedef Locked_<ContainerAllocator> Type;

  Locked_()
    : header()
    , pos()  {
    }
  Locked_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pos(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::target_detection::msgLocked_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::target_detection::msgLocked_<ContainerAllocator> >> _pos_type;
  _pos_type pos;





  typedef boost::shared_ptr< ::target_detection::Locked_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::target_detection::Locked_<ContainerAllocator> const> ConstPtr;

}; // struct Locked_

typedef ::target_detection::Locked_<std::allocator<void> > Locked;

typedef boost::shared_ptr< ::target_detection::Locked > LockedPtr;
typedef boost::shared_ptr< ::target_detection::Locked const> LockedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::target_detection::Locked_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::target_detection::Locked_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::target_detection::Locked_<ContainerAllocator1> & lhs, const ::target_detection::Locked_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pos == rhs.pos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::target_detection::Locked_<ContainerAllocator1> & lhs, const ::target_detection::Locked_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace target_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::target_detection::Locked_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::target_detection::Locked_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::target_detection::Locked_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::target_detection::Locked_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::target_detection::Locked_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::target_detection::Locked_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::target_detection::Locked_<ContainerAllocator> >
{
  static const char* value()
  {
    return "45a17d35b91831599261552b888c7e20";
  }

  static const char* value(const ::target_detection::Locked_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x45a17d35b9183159ULL;
  static const uint64_t static_value2 = 0x9261552b888c7e20ULL;
};

template<class ContainerAllocator>
struct DataType< ::target_detection::Locked_<ContainerAllocator> >
{
  static const char* value()
  {
    return "target_detection/Locked";
  }

  static const char* value(const ::target_detection::Locked_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::target_detection::Locked_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"msgLocked[] pos\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: target_detection/msgLocked\n"
"string Class   \n"
"uint16 centerX\n"
"uint16 centerY \n"
"float64 centerX_3\n"
"float64 centerY_3\n"
"float64 centerZ_3\n"
"float64 angleX\n"
"float64 angleY\n"
;
  }

  static const char* value(const ::target_detection::Locked_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::target_detection::Locked_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Locked_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::target_detection::Locked_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::target_detection::Locked_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pos[]" << std::endl;
    for (size_t i = 0; i < v.pos.size(); ++i)
    {
      s << indent << "  pos[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::target_detection::msgLocked_<ContainerAllocator> >::stream(s, indent + "    ", v.pos[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TARGET_DETECTION_MESSAGE_LOCKED_H
