// Generated by gencpp from file target_detection/position.msg
// DO NOT EDIT!


#ifndef TARGET_DETECTION_MESSAGE_POSITION_H
#define TARGET_DETECTION_MESSAGE_POSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace target_detection
{
template <class ContainerAllocator>
struct position_
{
  typedef position_<ContainerAllocator> Type;

  position_()
    : Class()
    , centerX(0)
    , centerY(0)
    , angleX(0.0)
    , angleY(0.0)
    , distance(0.0)  {
    }
  position_(const ContainerAllocator& _alloc)
    : Class(_alloc)
    , centerX(0)
    , centerY(0)
    , angleX(0.0)
    , angleY(0.0)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _Class_type;
  _Class_type Class;

   typedef uint16_t _centerX_type;
  _centerX_type centerX;

   typedef uint16_t _centerY_type;
  _centerY_type centerY;

   typedef double _angleX_type;
  _angleX_type angleX;

   typedef double _angleY_type;
  _angleY_type angleY;

   typedef double _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::target_detection::position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::target_detection::position_<ContainerAllocator> const> ConstPtr;

}; // struct position_

typedef ::target_detection::position_<std::allocator<void> > position;

typedef boost::shared_ptr< ::target_detection::position > positionPtr;
typedef boost::shared_ptr< ::target_detection::position const> positionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::target_detection::position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::target_detection::position_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::target_detection::position_<ContainerAllocator1> & lhs, const ::target_detection::position_<ContainerAllocator2> & rhs)
{
  return lhs.Class == rhs.Class &&
    lhs.centerX == rhs.centerX &&
    lhs.centerY == rhs.centerY &&
    lhs.angleX == rhs.angleX &&
    lhs.angleY == rhs.angleY &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::target_detection::position_<ContainerAllocator1> & lhs, const ::target_detection::position_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace target_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::target_detection::position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::target_detection::position_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::target_detection::position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::target_detection::position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::target_detection::position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::target_detection::position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::target_detection::position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b33d03305c0dd807b7a4b6591831277";
  }

  static const char* value(const ::target_detection::position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b33d03305c0dd80ULL;
  static const uint64_t static_value2 = 0x7b7a4b6591831277ULL;
};

template<class ContainerAllocator>
struct DataType< ::target_detection::position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "target_detection/position";
  }

  static const char* value(const ::target_detection::position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::target_detection::position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string Class   \n"
"uint16 centerX\n"
"uint16 centerY \n"
"float64 angleX\n"
"float64 angleY\n"
"float64 distance\n"
;
  }

  static const char* value(const ::target_detection::position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::target_detection::position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Class);
      stream.next(m.centerX);
      stream.next(m.centerY);
      stream.next(m.angleX);
      stream.next(m.angleY);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::target_detection::position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::target_detection::position_<ContainerAllocator>& v)
  {
    s << indent << "Class: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.Class);
    s << indent << "centerX: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.centerX);
    s << indent << "centerY: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.centerY);
    s << indent << "angleX: ";
    Printer<double>::stream(s, indent + "  ", v.angleX);
    s << indent << "angleY: ";
    Printer<double>::stream(s, indent + "  ", v.angleY);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TARGET_DETECTION_MESSAGE_POSITION_H
