// Generated by gencpp from file target_detection/Positions.msg
// DO NOT EDIT!


#ifndef TARGET_DETECTION_MESSAGE_POSITIONS_H
#define TARGET_DETECTION_MESSAGE_POSITIONS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <target_detection/position.h>

namespace target_detection
{
template <class ContainerAllocator>
struct Positions_
{
  typedef Positions_<ContainerAllocator> Type;

  Positions_()
    : header()
    , positions()  {
    }
  Positions_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , positions(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::target_detection::position_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::target_detection::position_<ContainerAllocator> >> _positions_type;
  _positions_type positions;





  typedef boost::shared_ptr< ::target_detection::Positions_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::target_detection::Positions_<ContainerAllocator> const> ConstPtr;

}; // struct Positions_

typedef ::target_detection::Positions_<std::allocator<void> > Positions;

typedef boost::shared_ptr< ::target_detection::Positions > PositionsPtr;
typedef boost::shared_ptr< ::target_detection::Positions const> PositionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::target_detection::Positions_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::target_detection::Positions_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::target_detection::Positions_<ContainerAllocator1> & lhs, const ::target_detection::Positions_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.positions == rhs.positions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::target_detection::Positions_<ContainerAllocator1> & lhs, const ::target_detection::Positions_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace target_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::target_detection::Positions_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::target_detection::Positions_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::target_detection::Positions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::target_detection::Positions_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::target_detection::Positions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::target_detection::Positions_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::target_detection::Positions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a4f03400a6799565fe19cfbc22b7c85";
  }

  static const char* value(const ::target_detection::Positions_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a4f03400a679956ULL;
  static const uint64_t static_value2 = 0x5fe19cfbc22b7c85ULL;
};

template<class ContainerAllocator>
struct DataType< ::target_detection::Positions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "target_detection/Positions";
  }

  static const char* value(const ::target_detection::Positions_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::target_detection::Positions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"position[]  positions\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: target_detection/position\n"
"string Class   \n"
"uint16 centerX\n"
"uint16 centerY \n"
"float64 angleX\n"
"float64 angleY\n"
"float64 distance\n"
;
  }

  static const char* value(const ::target_detection::Positions_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::target_detection::Positions_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Positions_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::target_detection::Positions_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::target_detection::Positions_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::target_detection::position_<ContainerAllocator> >::stream(s, indent + "    ", v.positions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TARGET_DETECTION_MESSAGE_POSITIONS_H
